sonar.projectKey=taller_ci_cd
sonar.projectName=Taller CI/CD
sonar.projectVersion=1.0.0
sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**,.github/**,dist/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
