sonar.projectKey=Gabriel-Ariza_CI_CD
sonar.projectName=CI_CD
sonar.organization=gabriel-ariza
sonar.projectVersion=1.0.0
sonar.sources=.
sonar.exclusions=node_modules/**,coverage/**,.github/**,dist/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8