name: Mi Primer CI
on: [push] # Se activa cada vez que haces push

jobs:
  verificacion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Descarga tu código en el servidor de GitHub
      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install # Instala Jest
      - run: npm test    # Ejecuta el test que creamos arriba