name: Pipeline Calidad
on: [push]

jobs:
  calidad-y-analisis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      # Pin v4.2.2

      # 0. INSTALAR DEPENDENCIAS
      - name: Instalar dependencias
        run: npm install

      # 1. VERIFICACIÓN DE ESTILO (Prettier)
      - name: Verificar formato con Prettier
        run: npm run format:check

      # 2. ANÁLISIS DE SONARCLOUD
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9
        # pin v7 a31c9398be7ace6bbfaf30c0bd5d415f843d45e9

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Gabriel-Ariza_CI_CD
            -Dsonar.organization=gabriel-ariza
            -Dsonar.qualitygate.wait=true

  despliegue:
    needs: calidad-y-analisis # Solo corre si lo anterior salió bien (CD)
    runs-on: ubuntu-latest
    permissions:
      contents: write # Para poder desplegar codigo
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      # Pin v4.2.2
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
        # Pin v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          cname: # Descomentar y añadir tu dominio si tienes uno personalizado