name: Pipeline Calidad
on: [push]

jobs:
  calidad-y-analisis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      # Pin v4.2.2

      # 0. INSTALAR DEPENDENCIAS
      - name: Instalar dependencias
        run: npm install

      # 1. VERIFICACIÓN DE ESTILO (Prettier)
      - name: Verificar formato con Prettier
        run: npm run format:check

      # 2. ANÁLISIS DE SONARCLOUD
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0 # pin@030132338505e612984144e54c73656334582f3a

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=CI_CD
            -Dsonar.organization=gabriel-ariza
            -Dsonar.qualitygate.wait=false

  despliegue:
    needs: calidad-y-analisis # Solo corre si lo anterior salió bien (CD)
    runs-on: ubuntu-latest
    permissions:
      contents: write # Para poder desplegar codigo
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      # Pin v4.2.2
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc66107dbfe9bd222d6859600100742569b31
        # Pin v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          cname: # Descomentar y añadir tu dominio si tienes uno personalizado